### ISSUE TITLE
Multiple sentries per signer in config

### ISSUE THREAD

**Issue by pratikbin** [strangelove-ventures/horcrux#100]
**Q**. In your [los-alamos](https://github.com/strangelove-ventures/los-alamos/blob/aeb6b7d522ccc6e921e674ec4f02c723f46dfd3c/examples/horcrux/cosmoshub/horcrux_signer_2.yaml#L76), when configuring hrocrux, you've specified multiple sentries `"tcp://192.168.5.4:31234,tcp://192.168.5.3:31234,tcp://192.168.5.5:31234"` one to many (one signer with multiple sentry) but in [migration docs](https://github.com/strangelove-ventures/horcrux/blob/main/docs/migrating.md#2-setup-signer-nodes) `"tcp://10.168.0.1:1234"` one to one (one signer with one sentry). May I know how would it affect the singing or fault tolerance?

```
$ horcrux config init cosmoshub-4 "tcp://192.168.5.4:31234,tcp://192.168.5.3:31234,tcp://192.168.5.5:31234" -c -p "tcp://signer-1:2222|1,tcp://signer-3:2222|3" -l "tcp://signer-2:2222" -k "/root/share/share.json" -t 2 --timeout 1500ms
```

```
$ horcrux config init {my_chain_id} "tcp://10.168.0.1:1234" -c -p "tcp://10.168.1.2:2222|2,tcp://10.168.1.3:2222|3" -l "tcp://10.168.1.1:2222" -t 2 --timeout 1500ms
```

**Comment by agouin** [comment]
One signer per sentry will result in faster signing overall at the cost of slightly less availability.  Signers connected to all sentries will result in higher availability at the cost of potentially longer block sign duration.

When sentries have multiple signers connected to them, the sentry will only send block sign requests to a single signer (this might not be the leader). If a non-leader signer receives a block sign request from a sentry, it will proxy the request to the leader, which means an additional round trip is added to the overall block sign time.

Let's compare fault tolerance for a 3 sentry and 3 signer configuration:

### Signer per sentry:
#### Fault Tolerance:
the cluster can tolerate any 2 sentries down as long as all signers are up. if a signer is down, the cluster can tolerate 2 sentries down in addition as long as one of the signers that is still up is connected to the sentry that is still up. If not, you can have a situation where 1 sentry is up and 2 signers are up, but since the downed signer was the one that connected to the up sentry, there is no longer any connection between the signers and sentries.

#### Performance
Since each signer only connects to a single sentry, this means that the leader signer will be receiving block sign requests directly from it's sentry, so it will likely always be faster than the proxy requests from the other two. Only during fault conditions might the cluster need to rely upon a proxy request in order to successfully sign a block (e.g. leader does not have a connection to its sentry, but one of the other signers still has a connection to its sentry).


### Signers connect to all sentries
#### Fault Tolerance
The cluster can tolerate any 2 sentries down and any 1 signer down. There is no caveat like the signer-per-sentry since all signers connect to all sentries. 

#### Performance
This configuration can slow down block sign times since the connected sentries may not send the block sign requests to the leader (e.g. one of the other non-leaders could receive all of the block sign requests from all the sentries for the same block, needing to proxy over to the leader). Depending on the block time of the chain and the latency between signers/sentries, this might not be fast enough to sign 100% of blocks.

#### Summary
- Choose signer per sentry for better overall block sign performance at the cost of a slight loss in fault tolerance.
- Choose signers connected to all sentries for better fault tolerance at the cost of slightly longer average block sign durations. If latencies are low so that 100% block sign can be achieved, this is a good choice.

**Comment by pratikbin** [comment]
Totally make sense, Thank you for clear explanation @agouin

**Comment by activenodes** [comment]
@agouin thank you for your explanation!
What do you think of this "hybrid" setup ?

2 Datacenter (with in each: 1 sentry and 1 signer)
1 Spare Datacenter (with 1 signer and without sentry)

```
DC01
Sentry01 <-> Signer01 <->|toS.2+3

DC02
Sentry02 <-> Signer02 <->|toS.1+2

DC03
             Signer03 <->|toS.1+2
```

this way each sentry is connected to its own local signer (latency 0) and there is an additional signer reachable p2p by the other signers when a DC is down.

I think it's the minimum configuration, but with high performance and full redundancy.

Signers connect to all sentries may cause connections cross like Sentry01<->Signer02 and Sentry02<->Signer01. Right?

Thanks
