### ISSUE TITLE
Which sentry is being utilized for signing?

### ISSUE THREAD

**Issue by pratikbin** [strangelove-ventures/horcrux#121]
Is there any way to know which sentry is being utilized for signing, so we can use the other sentries for other purpose. 

A raft leader metric that show `signer_sentry <signer_url_from_chain-nodes>` or `signer_sentry <chain-nodes_number>` then that would be great, others (non raft leader signer) should show `signer_sentry NA` or something

Any thoughts?

**Comment by agouin** [comment]
Hi @pratikbin, all configured sentries send block sign requests to the horcrux signers. They all receive the signature from the horcrux cluster and broadcast it to the other validators.

Horcrux requires a minimum of one configured sentry to function. However, only one sentry leads to a non-HA setup since that sentry becomes the single point of failure.

**Comment by pratikbin** [comment]
> They all receive the signature from the horcrux cluster and broadcast it to the other validators

I think I got you. Will comment here if any further info requires. Thank you, @agouin
