### ISSUE TITLE
block under 1 second

### ISSUE THREAD

**Issue by electrone13** [strangelove-ventures/horcrux#214]
can horcrux in 3 signers 3 node with 100-200ms between the signers and similar with nodes sign blockchains with block time equal or less than 1 second , if yes how to achieve that and what could be the bottle necks that will prevent achieving this

Thanks

**Comment by agouin** [comment]
Those RTTs will be too long to sign 1 second blocks consistently, as you will have the following for a block:

Time to receive proposal from proposer via p2p network
\+ time from sentry to cosigner (assume it's the leader, otherwise will need another trip to the leader) (50-100ms + 100-200ms if not directly to the leader)
\+ time from leader to other cosigner(s) for encrypted nonces request (100-200ms)
\+ time from leader to other cosigner(s) to spread nonces + payload for signature and request signature (100-200ms)
\+ time from leader back to sentry (50-100ms)
\+ time from sentry back to other validators via p2p

This means your total time to sign and share a vote with other validators is >300-800ms, since it does not include the negligible compute time along the way plus the RTT from your sentry(ies) to the other validators via p2p. Two votes are needed to sign a block (prevote and precommit), so this will barely be fast enough in the best case.

We are able to reliably sign 1 second blocks with a RTT of ~30ms between cosigners and sentries, but we do see missed blocks here and there. This allows us to maintain an uptime of >=99.2% in the slashing period window.

**Comment by electrone13** [comment]
thanks @agouin for your great illustration about this . and yes it will be very hard to compete with ( one node signs all ) approach from the speed and performance point . and maintain a ~30ms between ISPs or Different Sites will be very difficult 
Thanks again @agouin
