### ISSUE TITLE
Wrong "state" migrating from 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by activenodes** [strangelove-ventures/horcrux#228]
Migrating from version 3.1.0 to 3.2.0 no signatures occur with this error

`Cosigner failed to set nonces and sign       chain_id=xxx-1 height=xxx round=0 type=prevote cosigner=1 err="unexpected state, metadata does not exist for U: xxxxx"`

The steps performed:

- stop all sentry/nodes
- stop all signers
- update bin
- rm -rf /raft
- start all signers
- start sentry/nodes

The same in test with a stand-alone setup (--accept-risk) with a wrong state file.
In this last case I solved it increasing blocks without signatures and then by deleting `state/priv_validator_state.json` (it's a testnet)

Some idea?
Thanks

**Comment by agouin** [comment]
This is unrelated to the state files. I would avoid deleting the state files since that is a core part of horcrux' double sign protection. Waiting for blocks without signature is not always sufficient since an out of sync sentry could request a signature for an old block.

This is due to the cosigner nonce cache, and I believe it is related to #226 and think it may also be fixed by #227 in v3.2.1. Can you please try v3.2.1?
