### ISSUE TITLE
Failed to sign vote

### ISSUE THREAD

**Issue by maiquanghiep** [strangelove-ventures/horcrux#54]
We have a horcrux setup with 3 signers up and running but proposal block can be committed [#30 ](https://github.com/strangelove-ventures/horcrux/issues/30).
As the Raft feature is implemented, I added "raft-listen" and "raft-add" into the config.yaml but horcrux service is unable to sign the vote as below error
`Feb 07 01:52:08 infra-m-signer-3-ln-sg horcrux[885633]: D[2022-02-07|01:52:08.569] I am not the raft leader. Proxying request to the leader module=validator
Feb 07 01:52:08 infra-m-signer-3-ln-sg horcrux[885633]: E[2022-02-07|01:52:08.569] Failed to sign vote                          module=validator address=tcp://192.46.230.248:1234 error="unable to find leader cosigner from address 66.228.50.77:10023" vote_type=SIGNED_MSG_TYPE_PRECOMMIT height=4114554 round=0 validator=160D942A71109538206E0A897DEBDBF8DDB06BD4`

**Comment by agouin** [comment]
Is `66.228.50.77:10023` the raft bind address of one of your signers, but you are using a different address in the raft peers? They need to be the same address in v2.0.0-beta2. I have a PR up in #51  to solve this, as I ran into the same thing when setting up horcrux within a kubernetes service, as the bind address is not the same as what's given in the peers list due to kubernetes service routing where the node has a different IP than the pod.

**Comment by maiquanghiep** [comment]
The raft bind-address is same as raft-add in peers list
- Signer 1
```
cosigner:
   raft-listen: 66.228.50.77:10023
```
- Signer 2
 ```
peers:
  - share-id: 1
    raft-add: 66.228.50.77:10023
```

- Signer 3
 ```
peers:
  - share-id: 1
    raft-add: 66.228.50.77:10023
```

**Comment by agouin** [comment]
Might just be a config issue, `raft-add` should be `raft-addr`.

**Comment by maiquanghiep** [comment]
Oh!! Silly me, it should be raft-addr! Close the issue as signers are voting.
