### ISSUE TITLE
secure migration from 2.0.0-rc3 to 2.0.0

### ISSUE THREAD

**Issue by colossus-digital** [strangelove-ventures/horcrux#90]
is there a secure procedure/instructions for migrating an already working cluster from 2.0.0-rc3 to 2.0.0 ? (without downtime should be also great)
tnks

**Comment by agouin** [comment]
Yes, you can migrate from `v2.0.0-rc3` to `v2.0.0` without downtime using the update guide documented on the `v2.0.0-rc2` release: https://github.com/strangelove-ventures/horcrux/releases/tag/v2.0.0-rc2

You can perform a rolling update using `horcrux elect` so that the leader is never taken down during the process. For example:
1. Execute `horcrux elect 1` on any of the horcrux nodes, this will elect node 1 as the leader
2. Update and restart horcrux on node 2
3. Update and restart horcrux on node 3
4. Execute `horcrux elect 2` on any of the horcrux nodes, this will elect node 2 as the leader
5. Update and restart horcrux on node 1

**Comment by colossus-digital** [comment]
cool, my thought was that the two versions were not compatible
thank you for your help

**Comment by agouin** [comment]
happy to help!
